apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
      type: api
  template:
    metadata:
      labels:
        app: proxy
        type: api
    spec:
      containers:
        - name: api
          image: vmerv/analytics-proxy
          env:
            - name: CUSTOMER_CACHE_SERVICE
              value: cache-customer.customer.svc.cluster.local:8080
            - name: CUSTOMER_DB_SERVICE
              value: db-customer.customer.svc.cluster.local:8080
          ports:
            - name: main
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
spec:
  selector:
    app: proxy
    type: api
  ports:
    - name: main
      port: 8080
      targetPort: 8080
