apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: customer
  name: cache
  labels:
    type: cache
    target: redis
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cache
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/customer/cache
    type: DirectoryOrCreate

