apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: customer
  name: api-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
      type: api
      mode: cache
  template:
    metadata:
      namespace: customer
      labels:
        app: customer
        type: api
        mode: cache
    spec:
      containers:
        - name: api
          env:
            - name: MODE
              value: CACHE
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: db-url
            - name: CACHE_URL
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: cache-url
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: cache-password
          image: vmerv/analytics-customer
          ports:
            - name: main
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-cache
spec:
  selector:
    app: customer
    type: api
    mode: cache
  ports:
    - name: main
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: customer
  name: api-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
      type: api
      mode: db
  template:
    metadata:
      namespace: customer
      labels:
        app: customer
        type: api
        mode: db
    spec:
      containers:
        - name: api
          env:
            - name: MODE
              value: DB
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: customer-secrets
                  key: db-url
          image: vmerv/analytics-customer
          ports:
            - name: main
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
spec:
  selector:
    app: customer
    type: api
    mode: db
  ports:
    - name: main
      port: 80
      targetPort: 8080
