apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage
  labels:
    type: storage
    target: database
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: database
  hostPath:
    path: /data/customer/database
    type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-set
  labels:
    type: database
    tech: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres
      app: database
  template:
    metadata:
      labels:
        db: postgres
        app: database
    spec:
      containers:
        - name: db
          image: postgres
          env:
            - name: POSTGRES_DB
              value: customerdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: POSTGRES_USER
              value: docker
          ports:
            - name: main
              containerPort: 5432
          volumeMounts:
            - name: db-claim
              mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
    - metadata:
         name: db-claim
      spec:
        resources:
          requests:
            storage: 5Gi
        storageClassName: database
        selector:
          matchLabels:
            type: storage
            target: database
        volumeMode: Filesystem
        accessModes:
          - ReadWriteMany
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    db: postgres
    app: database
  ports:
    - name: main
      targetPort: 5432
      port: 5432
