---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: customer
  name: db-set
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      usage: handler
  template:
    metadata:
      namespace: customer
      labels:
        app: postgres
        usage: handler
    spec:
      containers:
        - name: db
          image: postgres:alpine
          env:
            - name: POSTGRES_DB
              value: customerdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: POSTGRES_USER
              value: docker
          ports:
            - name: main
              containerPort: 5432
          volumeMounts:
            - name: db-claim
              mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
    - metadata:
        namespace: customer
        name: db-claim
      spec:
        resources:
          requests:
            storage: 5Gi
        storageClassName: database
        selector:
          matchLabels:
            app: postgres
            usage: storage
        volumeMode: Filesystem
        accessModes:
          - ReadWriteMany
---
apiVersion: v1
kind: Service
metadata:
  namespace: customer
  name: db-service
spec:
  selector:
    app: postgres
    usage: handler
  ports:
    - name: main
      targetPort: 5432
      port: 5432
