apiVersion: v1
kind: PersistentVolume
metadata:
  name: init-customer
  labels:
    app: postgres
    usage: init
    service: customer
spec:
  capacity:
    storage: 800Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: init
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /init/customer
    type: DirectoryOrCreate
