apiVersion: v1
kind: PersistentVolume
metadata:
  name: init
  labels:
    type: init
    target: postgres
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: init
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /init/customer
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
    limits:
      storage: 500Mi
  storageClassName: init
  selector:
    matchLabels:
      type: init
      target: postgres
---
apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    metadata:
      labels:
        type: seeder
    spec:
      volumes:
        - name: init
          persistentVolumeClaim:
            claimName: init-claim 
      containers:
        - name: seeder
          image: vmerv/analytics-seeder-customer
          env:
            - name: OUTPUT_MEDIUM
              value: FILE
            - name: OUTPUT_DESTINATION
              value: /init/init.sql
            - name: ROWS_NUMBER
              value: "customers:1000000,transcations:4000000"
          volumeMounts:
            - name: init
              mountPath: /init
      restartPolicy: Never
  backoffLimit: 4
