apiVersion: v1
kind: PersistentVolume
metadata:
  name: init
  labels:
    app: postgres
    usage: init
spec:
  capacity:
    storage: 800Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: init
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /init/customer
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 800Mi
    limits:
      storage: 1Gi
  storageClassName: init
  selector:
    matchLabels:
      app: postgres
      usage: init
---
apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    metadata:
      labels:
        type: seeder
    spec:
      volumes:
        - name: init
          persistentVolumeClaim:
            claimName: init-claim 
      containers:
        - name: seeder
          image: vmerv/analytics-seeder-customer
          env:
            - name: OUTPUT_MEDIUM
              value: FILE
            - name: OUTPUT_DESTINATION
              value: /init
            - name: ROWS_NUMBER
              value: "customers:1000000,transactions:4000000"
          volumeMounts:
            - name: init
              mountPath: /init
      restartPolicy: Never
  backoffLimit: 4
