apiVersion: v1
kind: Service
metadata:
  name: customer-db
  labels:
    type: service
spec:
  selector:
    app: customer
    type: api
    mode: db
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: 8080
