apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: /bulk
            pathType: Prefix
            backend:
              service:
                name: proxy-svc
                port:
                  number: 8080
