apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-storage
  labels:
    app: redis
    usage: storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cache
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/{{ns}}/cache
    type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache-set
spec:
  selector:
    matchLabels:
      app: redis
      usage: handler
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        usage: handler
    spec:
      containers:
        - name: redis
          command: [ "sh", "-c", "redis-server --requirepass $REDIS_PASSWORD" ]
          image: redis:alpine
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: cache-password
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: cache
        volumeMode: Filesystem
        resources:
          requests:
            storage: 3Gi
          limits:
            storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app: redis
    usage: service
spec:
  selector:
    app: redis
    usage: handler
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
