apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-storage
  labels:
    app: postgres
    usage: storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: database
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/{{ns}}/database
    type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-set
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      usage: handler
  template:
    metadata:
      labels:
        app: postgres
        usage: handler
    spec:
      containers:
        - name: db
          image: postgres:alpine
          env:
            - name: POSTGRES_DB
              value: {{db-name}}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: POSTGRES_USER
              value: docker
          ports:
            - name: main
              containerPort: 5432
          volumeMounts:
            - name: db-claim
              mountPath: /var/lib/pgsql/data
            - name: init-claim
              mountPath: /docker-entrypoint-initdb.d/
  volumeClaimTemplates:
    - metadata:
        name: db-claim
      spec:
        resources:
          requests:
            storage: 5Gi
        storageClassName: database
        selector:
          matchLabels:
            app: postgres
            usage: storage
        volumeMode: Filesystem
        accessModes:
          - ReadWriteMany
    - metadata:
        name: init-claim
      spec:
        accessModes:
          - ReadWriteMany
        volumeMode: Filesystem
        resources:
          requests:
            storage: 200Mi
          limits:
            storage: 500Mi
        storageClassName: init
        selector:
          matchLabels:
            app: postgres
            usage: init
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: postgres
    usage: handler
  ports:
    - protocol: TCP
      targetPort: 5432
      port: 5432
