apiVersion: v1
kind: PersistentVolume
metadata:
  name: init-transaction
  labels:
    app: postgres
    usage: init
    service: transaction
spec:
  capacity:
    storage: 800Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: init
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /init/transaction
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: init-product
  labels:
    app: postgres
    usage: init
    service: product
spec:
  capacity:
    storage: 800Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: init
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /init/product
    type: DirectoryOrCreate
