apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
      type: api
      mode: cache
  template:
    metadata:
      labels:
        app: transaction
        type: api
        mode: cache
    spec:
      containers:
        - name: api
          image: vmerv/analytics-transaction
          env:
            - name: MODE
              value: CACHE
            - name: PRODUCT_SERVICE
              value: cache-product.product.svc.cluster.local:8080
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: db-url
            - name: CACHE_URL
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: cache-url
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: cache-password
          ports:
            - name: main
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cache-transaction
spec:
  selector:
    app: transaction
    type: api
    mode: cache
  ports:
    - name: main
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
      type: api
      mode: db
  template:
    metadata:
      labels:
        app: transaction
        type: api
        mode: db
    spec:
      containers:
        - name: api
          image: vmerv/analytics-transaction
          env:
            - name: MODE
              value: DB
            - name: PRODUCT_SERVICE
              value: db-product.product.svc.cluster.local:8080
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: db-url
          ports:
            - name: main
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: db-transaction
spec:
  selector:
    app: transaction
    type: api
    mode: db
  ports:
    - name: main
      port: 8080
      targetPort: 8080
